<a href="https://colab.research.google.com/github/philipjpark/Summer_22_Data_Analytics_HW4/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Problem 1:**

Write a Python/NumPy code block that finds the distinct/unique common items between these two
arrays:
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
Your output should contain only the distinct overlapping values. For example, if a 2 is found in both array a and array b,
your output should contain only one 2 even if array a contains more than one 2 within it.



**Problem 2:**

Create the following 5x3 array using knowledge you have of Python’s / NumPy’s sequencing functionality
so that you do not need to explicitly key in every integer value.
1   6    11
2   7    12
3   8    13
4   9    14
5   10  15



**Problem 3:**

The process of transforming a multidimensional array into a unidimensional array is referred to as “flattening”. Transform the 5x3 array shown above in Problem 2 into a unidimensional array such that the sequence of values contained within the array is as follows: 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15



**Problem 4:**

Transform the 2-D array shown in Problem 2 into a 3 dimensional array such that the first column becomes the first dimension of the 3-D array, the second column becomes the second dimension of the 3-D array, and the third column becomes the third dimension of the 3-D array.



**Problem 5:**

Transform the 3-D array you created in Problem 4 back to the 2-dimensional format shown in Problem 2.



**Problem 6:**

You are given the following two arrays:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])
Write a Python/Numpy code block that removes from array a any items that are also present in array b.



**Problem 7:**

Answer the following questions about the accompanying data file.

What is the maximum yearly NYC consumption of water in millions of gallons per day?
How many calendar years are represented within this data set? NumPy's shape command is one way to find
out.
What is the mean and the standard deviation of the per capita daily water consumption?
What is the increase or decrease in population from year to year? Use NumPy's `diff` function to create an array
of differences and save that to a variable called "pop_diff", then print that variable to the screen.

**Problem 1**

The intersect method finds the unique items in two arrays. 

In [32]:
import numpy as np
  
a = np.array([1, 2, 3, 2, 3, 4, 3, 4, 5, 6])
b = np.array([7, 2, 10, 2, 7, 4, 9, 4, 9, 8])
  
print(np.intersect1d(a, b))

[2 4]


**Problem 2**

The reshape method allows the array to be reformatted based on the rows and columns. 

In [7]:


newArr = np.array([1, 6, 11, 2, 7, 12, 3, 8, 13, 4, 9, 14, 5, 10, 15]).reshape(5,3)

print(newArr)


[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


**Problem 3**

The flatten method is great; it creates a 1D array. 

In [8]:
flatArr = newArr.flatten()

print(flatArr)

[ 1  6 11  2  7 12  3  8 13  4  9 14  5 10 15]


**Problem 4**
I need to better understand what this question is actually asking. I will go over the code and documentation so that I can figure out what the output should be.

**Resource:** https://stackoverflow.com/questions/7372316/how-to-make-a-2d-numpy-array-a-3d-array

In [16]:
threeDimArr = np.reshape(newArr, newArr.shape + (1,))
print(threeDimArr)

[[[ 1]
  [ 6]
  [11]]

 [[ 2]
  [ 7]
  [12]]

 [[ 3]
  [ 8]
  [13]]

 [[ 4]
  [ 9]
  [14]]

 [[ 5]
  [10]
  [15]]]


**Problem 5**

I merely reshaped the 3D array back to a 2D array by inputting the correct rows and columns. 

In [23]:
backTo2D = threeDimArr.reshape(5,3)
print(backTo2D)

[[ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]
 [ 5 10 15]]


**Problem 6**

The setdiff1d method is useful and I will learn how to leverage it in order to improve my skill-sets. 

In [27]:
a = np.array([12, 5, 7, 15, 3, 1, 8])
b = np.array([14, 6, 3, 11, 19, 12, 5])

unique = np.setdiff1d(a, b)
print(unique)

[ 1  7  8 15]


**Problem 7**

I am having hard time bringing up the file for the assignment into Colab. The files in my GitHub will not even show the raw data. I need to figure out how to fix this issue. 



In [24]:
df = pd.read_csv("https://raw.githubusercontent.com/philipjpark/Summer_22_Data_Analytics_HW4/master/blob/Module6_Data.csv")
df.head()


HTTPError: ignored

In [ ]:
import pandas as pd

data = pd.read_csv("Module6_Data (1).xlsx")
data